stages:
  - prepare
  - build
  - publish

prepare:
  image: ${LINBIT_DOCKER_REGISTRY}/build-helpers:latest
  stage: prepare
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_TAG
  variables:
    # git describe needs full history access
    GIT_DEPTH: 0
    # git describe does not need the submodule
    GIT_SUBMODULE_STRATEGY: none
  script:
    - SEMVER="$(semver-from-git.py)"
    - echo "SEMVER=${SEMVER}" >> .ci-build.env
    - echo "TAG=v${SEMVER/+/-}" >> .ci-build.env
    - echo "IMAGE=${LINBIT_DOCKER_REGISTRY}/drbd-shutdown-guard:v${SEMVER/+/-}" >> .ci-build.env
  artifacts:
    reports:
      dotenv: .ci-build.env

build:
  stage: build
  image: ${LINBIT_DOCKER_REGISTRY}/container-tools:latest
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_DEPTH: 1
    NOCACHE: "false"
    # Release for tnf-drbd-fencing.py
    DRBD_UTILS_SRC: ${LINBIT_REGISTRY_URL}/repository/lbbuild-upstream/drbd-utils-9.0.0.916c1de8edb4db559cc6db483838ba1f3253b73a.tar.gz
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_TAG
      variables:
        NOCACHE: "true"
  script:
    - docker buildx build --pull --push --platform ${PUBLISH_PLATFORMS} -t ${IMAGE} --build-arg=VERSION=${SEMVER} --build-arg=DRBD_UTILS_SRC=${DRBD_UTILS_SRC} --no-cache="${NOCACHE}" .

publish:
  stage: publish
  variables:
    DOCKER_AUTH_CONFIG_FROM: DOCKER_PUBLISH_AUTH_CONFIG_FILE
  rules:
    - if: $CI_COMMIT_TAG
  image: ${LINBIT_DOCKER_REGISTRY}/container-tools:latest
  script:
    - for PLATFORM in $(echo $PUBLISH_PLATFORMS | tr ',' '\n') ; do
    -   ARCH=${PLATFORM#*/}
    -   crane copy --platform $PLATFORM $IMAGE $PUBLISH_REGISTRY/$ARCH/drbd-shutdown-guard:$TAG
    -   crane tag $PUBLISH_REGISTRY/$ARCH/drbd-shutdown-guard:$TAG latest
    - done
    - crane copy $IMAGE $PUBLISH_REGISTRY/drbd-shutdown-guard:$TAG
    - crane tag $PUBLISH_REGISTRY/drbd-shutdown-guard:$TAG latest
